### ISSUE TITLE
Window for the regular app does not follow the title bar 

### ISSUE THREAD

**Issue by Cateatacat** [ScratchFakemon/Firefly#1]
I tried the regular app and I saw that the window doesn't follow the title bar

**Comment by ScratchFakemon** [comment]
OK

**Comment by ScratchFakemon** [comment]
I tested it, and I don't see your issue. Your computer might be 
### l a g g i n g 
or something

**Comment by webbrowser11** [comment]
he means its not always at the same position as the title bar. it wiggles around.

**Comment by webbrowser11** [comment]
neither does the exit thing if you look closely.

**Comment by webbrowser11** [comment]
or who knows maybe ITS NOT A BUG ITS A FEATURE!

**Comment by ScratchFakemon** [comment]
it's not my fault, it's a problem with the Clones+ extension.

**Comment by webbrowser11** [comment]
oh

**Comment by webbrowser11** [comment]
u should close this then
